### ISSUE TITLE
Screen keeps comming on after --off

### ISSUE THREAD

**Issue by Aergernis** [Tom-Hirschberger/MMM-Screen-Powersave-Notification#8]
Hi,
i made new installation of MM and had the probelm that the Screen won't stay off and always comes back after a few second after disabling.
After some searching i found  that there can be some issues with hotplug for HDMI. The solution was to add `vc4.force_hotplug=1` to `/boot/firmware/cmdline.txt`

`vc4.force_hotplug=1` for HMDI-0 only
`vc4.force_hotplug=2` for HMDI-1 only
`vc4.force_hotplug=3` if 2 Screens are connected (not tested by me)

Would be nice if you could include this in Wiki if someone else is running into the same problem.

**Comment by Tom-Hirschberger** [comment]
Hi,

and sorry for the late reply. Thanks for the info.
I will try to add a section to the readme in the next couple of days.

**Comment by Tom-Hirschberger** [comment]
Hi and thanks again.
I added your hints to a new section in the readme
